import {
  faBell,
  faBuilding,
  faCalendar,
  faCalendarAlt,
  faCaretSquareDown,
  faCaretSquareUp,
  faCheckCircle,
  faCircle,
  faClipboard,
  faCopy,
  faDotCircle,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFileAlt,
  faHeart,
  faImage,
  faLifeRing,
  faMinusSquare,
  faSave,
  faStar,
  faStickyNote,
  faTimesCircle,
  faTrashAlt,
  faUser,
  faUserCircle,
} from "@fortawesome/free-regular-svg-icons";

/**
 * naming convention:
 * (1) remove the "fa" prefix from the imported name
 * (2) add a "R" char at the end, to make it clear that is a regular-type icon
 * FontAwesome can have the same icon with the same name in different types, so make sure to name properly
 */
export const regularIcons = {
  bellR: faBell,
  buildingR: faBuilding,
  calendarAltR: faCalendarAlt,
  calendarR: faCalendar,
  caretSquareDownR: faCaretSquareDown,
  caretSquareUpR: faCaretSquareUp,
  checkCircleR: faCheckCircle,
  circleR: faCircle,
  clipboardR: faClipboard,
  copyR: faCopy,
  dotCircleR: faDotCircle,
  envelopeR: faEnvelope,
  eyeR: faEye,
  eyeSlashR: faEyeSlash,
  fileAltR: faFileAlt,
  heartR: faHeart,
  imageR: faImage,
  lifeRingR: faLifeRing,
  minusSquareR: faMinusSquare,
  saveR: faSave,
  starR: faStar,
  stickNoteR: faStickyNote,
  timesCircleR: faTimesCircle,
  trashAltR: faTrashAlt,
  userCircleR: faUserCircle,
  userR: faUser,
};
