import {
  faAlignCenter,
  faAlignLeft,
  faAlignRight,
  faArrowUp,
  faArrowUpRightFromSquare,
  faBars,
  faBackward,
  faBicycle,
  faBold,
  faBolt,
  faBook,
  faBurger,
  faCamera,
  faCaretDown,
  faCartShopping,
  faCaretLeft,
  faCaretRight,
  faCarSide,
  faCheck,
  faCheckDouble,
  faCheckSquare,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCog,
  faCross,
  faEllipsisH,
  faEllipsisV,
  faExclamation,
  faExclamationCircle,
  faFileInvoice,
  faFire,
  faFont,
  faForward,
  faGift,
  faHandHoldingHeart,
  faHeadset,
  faHighlighter,
  faHospital,
  faHouse,
  faInfoCircle,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faMinus,
  faMinusCircle,
  faMotorcycle,
  faPiggyBank,
  faPen,
  faPhone,
  faPlus,
  faPlane,
  faRedo,
  faShirt,
  faShield,
  faSlidersH,
  faSort,
  faSortDown,
  faSortUp,
  faStar,
  faTable,
  faTablet,
  faTimes,
  faTrash,
  faTriangleExclamation,
  faUnderline,
  faUndo,
  faUnlink,
  faUpload,
} from "@fortawesome/free-solid-svg-icons";

/**
 * naming convention:
 * (1) remove the "fa" prefix from the imported name
 * (2) add a "S" char at the end, to make it clear that is a solid-type icon
 * FontAwesome can have the same icon with the same name in different types, so make sure to name properly
 */
export const solidIcons = {
  alignCenterS: faAlignCenter,
  alignLeftS: faAlignLeft,
  alignRightS: faAlignRight,
  arrowUpRightFromSquareS: faArrowUpRightFromSquare,
  arrowUpS: faArrowUp,
  backwardS: faBackward,
  barsS: faBars,
  bicycleS: faBicycle,
  boldS: faBold,
  boltS: faBolt,
  bookS: faBook,
  burgerS: faBurger,
  caretDownS: faCaretDown,
  cameraS: faCamera,
  cartShoppingS: faCartShopping,
  caretLeftS: faCaretLeft,
  caretRightS: faCaretRight,
  carSideS: faCarSide,
  checkS: faCheck,
  checkDoubleS: faCheckDouble,
  checkSquareS: faCheckSquare,
  chevronDownS: faChevronDown,
  chevronLeftS: faChevronLeft,
  chevronRightS: faChevronRight,
  chevronUpS: faChevronUp,
  cogS: faCog,
  crossS: faCross,
  ellipsisHS: faEllipsisH,
  ellipsisVS: faEllipsisV,
  exclamationCircleS: faExclamationCircle,
  exclamationS: faExclamation,
  giftS: faGift,
  fireS: faFire,
  fileInvoiceS: faFileInvoice,
  fontS: faFont,
  forwardS: faForward,
  headsetS: faHeadset,
  handHoldingHeartS: faHandHoldingHeart,
  highlighterS: faHighlighter,
  hospitalS: faHospital,
  houseS: faHouse,
  infoCircleS: faInfoCircle,
  italicS: faItalic,
  linkS: faLink,
  listOlS: faListOl,
  listUlS: faListUl,
  minusCircleS: faMinusCircle,
  minusS: faMinus,
  motorcycleS: faMotorcycle,
  penS: faPen,
  phoneS: faPhone,
  piggyBankS: faPiggyBank,
  plusS: faPlus,
  planeS: faPlane,
  redoS: faRedo,
  slidersHS: faSlidersH,
  shirtS: faShirt,
  shieldS: faShield,
  sortDownS: faSortDown,
  sortS: faSort,
  sortUpS: faSortUp,
  starS: faStar,
  tableS: faTable,
  tabletS: faTablet,
  timesS: faTimes,
  trashS: faTrash,
  triangleExclamationS: faTriangleExclamation,
  underlineS: faUnderline,
  undoS: faUndo,
  unlinkS: faUnlink,
  uploadS: faUpload,
};
