name: Linting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
      env:
        CI: true
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - run: npm run test
      env:
        CI: true
